GET http://localhost:5169/linkage/all/on

###
GET http://localhost:5169/linkage/all/off

###
GET http://localhost:5169/linkage/onlyBack/on

###
GET http://localhost:5169/linkage/front/1

###
GET http://localhost:5169/linkage/front/on

###
GET http://localhost:5169/linkage/onlyBack/off